# fly.toml app configuration file generated for control-leads-gabiru on 2023-05-23T19:53:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "control-leads-gabiru"
primary_region = "gru"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
